services:
  simple-ots:
    #image: roura/simple-ots
    build:
      context: .
    network_mode: bridge
    container_name: simple-ots
    ports:
      - "80:80"
    restart: on-failure
    environment:
      AUTH_IP_RANGE: 192.168.0.
      # AUTH_IPS: 1.1.1.1,8.8.8.8
    volumes:
      - ./html:/var/www/html
